### ISSUE TITLE
Redirects are down?

### ISSUE THREAD

**Issue by lukaskollmer** [mammuth/TUM.sexy#282]
Trying to access eg `dwt.tum.sexy` results in chrome refusing to load the page, due to an ERR_SSL_PROTOCOL_ERROR

**Comment by reschandreas** [comment]
I guess that should be fixed by my merge request. The target was http:// and I changed it to https://

**Comment by kordianbruck** [comment]
Thanks @lukaskollmer for reporting this. Indeed I had a mess up with the wildcard certificate that is used for the subdomains, as it wasn't properly bound into the container. I've fixed the path (which has changed due to a recent update) and it seems that its working once again.

#283 was also useful, but did not fix this particular issue :)
